/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/inquiry/eval" |
       "/pages/admin/inquiry" |
       "/pages/admin/admin" |
       "/pages/diaryList/diaryList" |
       "/pages/feeling/feeling" |
       "/pages/ganyu/ganyu" |
       "/pages/ganyu/ganyu_temp" |
       "/pages/home/home" |
       "/pages/inquiry/end" |
       "/pages/inquiry/first" |
       "/pages/inquiry/inquiry" |
       "/pages/inquiry/start" |
       "/pages/inquiry/success" |
       "/pages/journey2/daolan1" |
       "/pages/journey2/daolan2" |
       "/pages/journey2/daoru2" |
       "/pages/journey_common/common" |
       "/pages/journey_common/daolanHome" |
       "/pages/journey_common/daolanStart" |
       "/pages/journey_common/start_journey" |
       "/pages/login/login" |
       "/pages/login/login_origin" |
       "/pages/mood/mood" |
       "/pages/my/my" |
       "/pages/my/my_new" |
       "/pages/my/my_origin" |
       "/pages/record/record" |
       "/pages/tabbar/tabbar" |
       "/pages/test2/test2" |
       "/pages/tool/tool";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/home" | "/pages/tool/tool" | "/pages/my/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
